language: node_js
node_js:
    - "8"

notifications:
  email: false

before_script:
  - npm install

script:
  - ./bin/vue-make mixin mixin
  - ./bin/vue-make store module
  - ./bin/vue-make directive directive
  - ./bin/vue-make view view
  - ./bin/vue-make component component